1: 001_chips_can
2: 002_master_chef_can
3: 003_cracker_box
4: 004_sugar_box
5: 005_tomato_soup_can
6: 006_mustard_bottle
7: 007_tuna_fish_can
8: 008_pudding_box
9: 009_gelatin_box
10: 010_potted_meat_can
11: 011_banana
12: 012_strawberry
13: 013_apple
14: 014_lemon
15: 015_peach
16: 016_pear
17: 017_orange
18: 018_plum
19: 019_pitcher_base
21: 021_bleach_cleanser
22: 022_windex_bottle
23: 023_wine_glass
24: 024_bowl
25: 025_mug
26: 026_sponge
27: 027-skillet
28: 028_skillet_lid
29: 029_plate
30: 030_fork
31: 031_spoon
32: 032_knife
33: 033_spatula
35: 035_power_drill
36: 036_wood_block
37: 037_scissors
38: 038_padlock
39: 039_key
40: 040_large_marker
41: 041_small_marker
42: 042_adjustable_wrench
43: 043_phillips_screwdriver
44: 044_flat_screwdriver
46: 046_plastic_bolt
47: 047_plastic_nut
48: 048_hammer
49: 049_small_clamp
50: 050_medium_clamp
51: 051_large_clamp
52: 052_extra_large_clamp
53: 053_mini_soccer_ball
54: 054_softball
55: 055_baseball
56: 056_tennis_ball
57: 057_racquetball
58: 058_golf_ball
59: 059_chain
61: 061_foam_brick
62: 062_dice
63-a: 063-a_marbles
63-b: 063-b_marbles
63-c: 063-c_marbles
63-d: 063-d_marbles
63-e: 063-e_marbles
63-f: 063-f_marbles
65-a: 065-a_cups
65-b: 065-b_cups
65-c: 065-c_cups
65-d: 065-d_cups
65-e: 065-e_cups
65-f: 065-f_cups
65-g: 065-g_cups
65-h: 065-h_cups
65-i: 065-i_cups
65-j: 065-j_cups
70-a: 070-a_colored_wood_blocks
70-b: 070-b_colored_wood_blocks
71: 071_nine_hole_peg_test
72-a: 072-a_toy_airplane
72-b: 072-b_toy_airplane
72-c: 072-c_toy_airplane
72-d: 072-d_toy_airplane
72-e: 072-e_toy_airplane
72-f: 072-f_toy_airplane
72-g: 072-g_toy_airplane
72-h: 072-h_toy_airplane
72-i: 072-i_toy_airplane
72-j: 072-j_toy_airplane
72-k: 072-k_toy_airplane
73-a: 073-a_lego_duplo
73-b: 073-b_lego_duplo
73-c: 073-c_lego_duplo
73-d: 073-d_lego_duplo
73-e: 073-e_lego_duplo
73-f: 073-f_lego_duplo
73-g: 073-g_lego_duplo
73-h: 073-h_lego_duplo
73-i: 073-i_lego_duplo
73-j: 073-j_lego_duplo
73-k: 073-k_lego_duplo
73-l: 073-l_lego_duplo
73-m: 073-m_lego_duplo
76: 076_timer
77: 077_rubiks_cube
